### ISSUE TITLE
Google changed the Merriweather font

### ISSUE THREAD

**Issue by dylans** [dojo/dojo-website#11]
Due to Google's changes to the Merriweather font ( https://www.google.com/fonts/specimen/Merriweather ), everything on dojotoolkit.org looks bold now, which does not seem ideal.

**Comment by sebilasse** [comment]
p.s.: the `font-weight: 300;` is now closer to the "perfect original" `400`.
p.p.s.: 
Ok, google > Is there a reason not to version webfonts ?

**Comment by davelab6** [comment]
Currently TypeKit is designed so that when you integrate a web font via their API, you will never be auto-upgraded, and Google Fonts is designed you are always auto-upgraded. 

The reason Google Fonts is like that is it intends to offer the most easy, no-brainer, path to using web fonts, and banks on users trust that upgrades will be beneficial. 

@EbenSorkin has redesigned Merriweather and believes the new weight is an improvement. If you think it isn't you should tell him, and he may update the font again to be lighter.

**Comment by davelab6** [comment]
Ah, indeed @sebilasse you already did contact Eben on the Merriweather issue comment - sorry, wasn't paying enough attention to usernames =)

**Comment by sebilasse** [comment]
@davelab6 And funny. Answered on the original thread and you already gave an answer to the answer here:
> Currently TypeKit is designed so that when you integrate a web font via their API, you will never be auto-upgraded, and Google Fonts is designed you are always auto-upgraded.

Did not know that.

> If you think it isn't you should tell him

Did that.

:+1: and thanks for your reply.

**Comment by kfranqueiro** [comment]
On Windows the new weight still doesn't look bad.  I'd argue it's actually better visibility-wise at least for black-on-white text.  I can see where the white-on-dark text looks a little heavy though, especially on Mac.

**Comment by sebilasse** [comment]
Below is a screenshot on Mac where 
the `300` has ligature issues and
the `400` appears very bold

<img width="264" alt="merriweather / mac" src="https://cloud.githubusercontent.com/assets/750300/12536681/6b2957cc-c2ac-11e5-92a0-e44dcb4a3bc9.png">

**Comment by davelab6** [comment]
@kfranqueiro thanks for offering your thoughts on this, will help @ebensorkin make the call

**Comment by davelab6** [comment]
@sebilasse looks like edge web fonts doesn't automatically update so you can switch to the older version with them, then switch back on monday afternoon to avoid the Firefox 44 release problems. Example, http://jsbin.com/kimilitihe/1/edit?html,output

**Comment by sebilasse** [comment]
@dylans @kfranqueiro - fyi – @davelab6 tweeted:
> @ebensorkin has made it better for windows users, and mac font rendering is always a bit darker than win

Conclusion: While the old version looked fine with the *default* OS X font rendering the new version definitely looks better in OS X with:

```css
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
```

It is closer to the windows weights, still a bit heavier but fine for my taste ...

**Comment by dylans** [comment]
Thanks @sebilasse @kfranqueiro @davelab6 @ebensorkin.

On a Mac, I would normally expect paragraph text to have a font weight comparable to: 

![Intern website](https://cloud.githubusercontent.com/assets/97291/12550612/321512b6-c322-11e5-8592-f5d1ab1a600c.png)

You could argue that font weight might be a touch light. That said, with the changes to Merriweather, by default (as noted above), everything looks bolded:

![Dojo website](https://cloud.githubusercontent.com/assets/97291/12550624/463946a4-c322-11e5-9ce0-9d4a1a42db8d.png)

**Comment by sebilasse** [comment]
@dylans 
Ok, I agree.
[What you expect](http://typecast.com/qyv9yQpJ37/share/c60d5008375dbb5e882810bc826382b29d3afe4794b) is
```
font-weight: 300;
-webkit-font-smoothing: subpixel-antialiased; /* default */
```
:point_up:  That is pretty similar to an article in theguardian.com ...
:point_down: while
```
font-weight: 400;
-webkit-font-smoothing: antialiased;
```
is pretty similar to an article in zeit.de ...

---
I would be curious to see a windows (edge) screenshot with `300` !
If it is not to thin, why not switch to `300` ?

reason: on the road and my MBP you saw in Amsterdam is no more. Since yesterday it's now just a display and I got a new one where I have to install windows on an external disk later (because of apples new "clump together" policy ;)

**Comment by dylans** [comment]
I believe this has been fixed.
